# Generated by Django 6.0.1 on 2026-01-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_subject_total_units_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabusitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='syllabusitem',
            name='order',
        ),
    ]
