# Generated by Django 6.0.1 on 2026-01-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_syllabusitem_options_remove_syllabusitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
